// Deprecated RAK4631 build-flag aliases.
//
// OPENHOP_* names are canonical. The legacy names remain accepted so an
// existing custom build cannot silently lose its TCP token, pin map, DHCP, or
// reset policy during the rename. When both are supplied, OPENHOP_* wins.
#pragma once

#if defined(PYMC_ETHERNET_W5100S) && !defined(OPENHOP_ETHERNET_W5100S)
#  define OPENHOP_ETHERNET_W5100S PYMC_ETHERNET_W5100S
#endif
#if defined(PYMC_ETH_TCP_PORT) && !defined(OPENHOP_ETH_TCP_PORT)
#  define OPENHOP_ETH_TCP_PORT PYMC_ETH_TCP_PORT
#endif
#if defined(PYMC_ETH_TOKEN) && !defined(OPENHOP_ETH_TOKEN)
#  define OPENHOP_ETH_TOKEN PYMC_ETH_TOKEN
#endif
#if defined(PYMC_ETH_HOSTNAME) && !defined(OPENHOP_ETH_HOSTNAME)
#  define OPENHOP_ETH_HOSTNAME PYMC_ETH_HOSTNAME
#endif
#if defined(PYMC_ETH_USE_DHCP) && !defined(OPENHOP_ETH_USE_DHCP)
#  define OPENHOP_ETH_USE_DHCP PYMC_ETH_USE_DHCP
#endif
#if defined(PYMC_ETH_DHCP_TIMEOUT_MS) && !defined(OPENHOP_ETH_DHCP_TIMEOUT_MS)
#  define OPENHOP_ETH_DHCP_TIMEOUT_MS PYMC_ETH_DHCP_TIMEOUT_MS
#endif
#if defined(PYMC_ETH_DHCP_RESPONSE_TIMEOUT_MS) && !defined(OPENHOP_ETH_DHCP_RESPONSE_TIMEOUT_MS)
#  define OPENHOP_ETH_DHCP_RESPONSE_TIMEOUT_MS PYMC_ETH_DHCP_RESPONSE_TIMEOUT_MS
#endif
#if defined(PYMC_ETH_DHCP_RETRY_MS) && !defined(OPENHOP_ETH_DHCP_RETRY_MS)
#  define OPENHOP_ETH_DHCP_RETRY_MS PYMC_ETH_DHCP_RETRY_MS
#endif
#if defined(PYMC_ETH_STATIC_FALLBACK_ON_DHCP_FAIL) && !defined(OPENHOP_ETH_STATIC_FALLBACK_ON_DHCP_FAIL)
#  define OPENHOP_ETH_STATIC_FALLBACK_ON_DHCP_FAIL PYMC_ETH_STATIC_FALLBACK_ON_DHCP_FAIL
#endif
#if defined(PYMC_ETH_STATIC_IP) && !defined(OPENHOP_ETH_STATIC_IP)
#  define OPENHOP_ETH_STATIC_IP PYMC_ETH_STATIC_IP
#endif
#if defined(PYMC_ETH_GATEWAY) && !defined(OPENHOP_ETH_GATEWAY)
#  define OPENHOP_ETH_GATEWAY PYMC_ETH_GATEWAY
#endif
#if defined(PYMC_ETH_SUBNET) && !defined(OPENHOP_ETH_SUBNET)
#  define OPENHOP_ETH_SUBNET PYMC_ETH_SUBNET
#endif
#if defined(PYMC_ETH_DNS) && !defined(OPENHOP_ETH_DNS)
#  define OPENHOP_ETH_DNS PYMC_ETH_DNS
#endif
#if defined(PYMC_ETH_POWER_PIN) && !defined(OPENHOP_ETH_POWER_PIN)
#  define OPENHOP_ETH_POWER_PIN PYMC_ETH_POWER_PIN
#endif
#if defined(PYMC_ETH_RESET_PIN) && !defined(OPENHOP_ETH_RESET_PIN)
#  define OPENHOP_ETH_RESET_PIN PYMC_ETH_RESET_PIN
#endif
#if defined(PYMC_ETH_CS_PIN) && !defined(OPENHOP_ETH_CS_PIN)
#  define OPENHOP_ETH_CS_PIN PYMC_ETH_CS_PIN
#endif
#if defined(PYMC_ETH_INT_PIN) && !defined(OPENHOP_ETH_INT_PIN)
#  define OPENHOP_ETH_INT_PIN PYMC_ETH_INT_PIN
#endif
#if defined(PYMC_ETH_SPI_SCK) && !defined(OPENHOP_ETH_SPI_SCK)
#  define OPENHOP_ETH_SPI_SCK PYMC_ETH_SPI_SCK
#endif
#if defined(PYMC_ETH_SPI_MISO) && !defined(OPENHOP_ETH_SPI_MISO)
#  define OPENHOP_ETH_SPI_MISO PYMC_ETH_SPI_MISO
#endif
#if defined(PYMC_ETH_SPI_MOSI) && !defined(OPENHOP_ETH_SPI_MOSI)
#  define OPENHOP_ETH_SPI_MOSI PYMC_ETH_SPI_MOSI
#endif
#if defined(PYMC_ETH_RESET_LOW_MS) && !defined(OPENHOP_ETH_RESET_LOW_MS)
#  define OPENHOP_ETH_RESET_LOW_MS PYMC_ETH_RESET_LOW_MS
#endif
#if defined(PYMC_ETH_POST_RESET_MS) && !defined(OPENHOP_ETH_POST_RESET_MS)
#  define OPENHOP_ETH_POST_RESET_MS PYMC_ETH_POST_RESET_MS
#endif
#if defined(PYMC_ETH_HARD_RESET_ON_BEGIN) && !defined(OPENHOP_ETH_HARD_RESET_ON_BEGIN)
#  define OPENHOP_ETH_HARD_RESET_ON_BEGIN PYMC_ETH_HARD_RESET_ON_BEGIN
#endif
#if defined(PYMC_ETH_ASSUME_UNKNOWN_LINK_UP) && !defined(OPENHOP_ETH_ASSUME_UNKNOWN_LINK_UP)
#  define OPENHOP_ETH_ASSUME_UNKNOWN_LINK_UP PYMC_ETH_ASSUME_UNKNOWN_LINK_UP
#endif
#if defined(PYMC_RAK4631_SX126X_POWER_EN) && !defined(OPENHOP_RAK4631_SX126X_POWER_EN)
#  define OPENHOP_RAK4631_SX126X_POWER_EN PYMC_RAK4631_SX126X_POWER_EN
#endif
